"""add_pickup_delivery_time_and_confirmed_at_to_orders

Revision ID: e5b1d9838c2e
Revises: a1842c666b8e
Create Date: 2025-09-09 11:32:16.483866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b1d9838c2e'
down_revision: Union[str, Sequence[str], None] = 'a1842c666b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pickup_delivery_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'confirmed_at')
    op.drop_column('orders', 'pickup_delivery_time')
    # ### end Alembic commands ###
